import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#274268",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  image: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  input: {
    margin: 5,
    borderRadius: 16,
    fontWeight: "bold",
    height: 50,
    width: "80%",
    paddingLeft: 20,
    fontSize: 18,
    borderColor: "white",
    backgroundColor: "#507dbc",
  },
  logo: {
    width: 120,
    height: 120,
  },
  loginButton: {
    backgroundColor: "#507dbc",
    borderColor: "white",
    color: "white",
    width: "80%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    fontSize: 24,
    fontWeight: "bold",
  },
  signupButton: {
    backgroundColor: "#a1c6ea",
    borderColor: "white",
    color: "white",
    width: "80%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    marginTop: 10,
    fontSize: 24,
    fontWeight: "bold",
  },
});
